kind: pipeline
type: docker
name: default

steps:
  - name: build-debug
    image: cimg/android:2021.08.1
    commands:
      - ./gradlew clean assembleDebug
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request
        - tag