kind: pipeline
type: docker
name: default

steps:
  - name: build-debug
    image: cimg/android:2021.08.1
    user: 0
    volumes:
      - name: gradle
        path: /root/.gradle
      - name: maven
        path: /root/.m2
    commands:
      - ./gradlew clean assembleDebug
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request
        - tag

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: release_key
      base_url: https://gitea.skygard.cn
      files: app/build/outputs/apk/debug/*
    when:
      event:
        - tag

volumes:
  - name: gradle
    host:
      path: $HOME/.gradle
  - name: maven
    host:
      path: $HOME/.m2